### ISSUE TITLE
new ADM setting will not be effective

### ISSUE THREAD

**Issue by ltutar** [biemond/biemond-orawls#355]
Hi,
I have the following hiera entry:
```
# create a standard domain
domain_instances:
  "%{hiera('wls_domain_name')}":
    domain_template:                       "%{hiera('domain_template')}"
    development_mode:                      false
    #adminserver_listen_on_all_interfaces:  true
    java_arguments:
      ADM:  "-XX:MaxPermSize=512m -Xms1024m -Xmx1024m -Dweblogic.security.SSL.minimumProtocolVersion=TLSv1"
    nodemanager_address:                   "%{hiera('adminserver_address')}"
    nodemanager_port:                      "%{hiera('node_manager_port')}"
    log_output:                            *logoutput
    nodemanager_secure_listener:           true
    adminserver_ssl_port:                  "%{hiera('admin_ssl_listen_port')}"
    custom_identity:                       true
    custom_identity_keystore_filename:     "/opt/ssl/keystore/identity_%{hiera('adminserver_fqdn')}.jks"
    custom_identity_keystore_passphrase:   "%{hiera('custom_identity_keystore_passphrase')}"
    custom_identity_alias:                 "%{hiera('adminserver_fqdn')}"
    custom_identity_privatekey_passphrase: "%{hiera('custom_identity_privatekey_passphrase')}"
```
and the following refresh:
```
# subscribe on a domain change and restart the adminserver
# subscribe on a adminserver change and restart the adminserver
wls_adminserver_instances_refresh:
  'AdminServer':
    ensure:                      'running'
    server_name:                 'AdminServer'
    domain_name:                 "%{hiera('wls_domain_name')}"
    domain_path:                 "%{hiera('wls_domains_dir')}/%{hiera('wls_domain_name')}"
    os_user:                     "%{hiera('wls_os_user')}"
    weblogic_home_dir:           "%{hiera('wls_weblogic_home_dir')}"
    weblogic_user:               "%{hiera('wls_user')}"
    weblogic_password:           "%{hiera('wls_password')}"
    nodemanager_address:         "%{hiera('adminserver_address')}"
    nodemanager_port:            "%{hiera('node_manager_port')}"
    nodemanager_secure_listener: true
    jsse_enabled:                true
    custom_trust:                "%{hiera('wls_custom_trust')}"
    trust_keystore_file:         "%{hiera('wls_trust_keystore_file')}"
    trust_keystore_passphrase:   "%{hiera('wls_trust_keystore_passphrase')}"
    refreshonly:                 true
    subscribe:
      - Wls_domain[%{hiera('wls_domain_name')}]
      - Wls_server[AdminServer]
```

when I change the value to:
```
      ADM:  "-XX:MaxPermSize=512m -Xms512m -Xmx512m -Dweblogic.security.SSL.minimumProtocolVersion=TLSv1"
```
Also no mention of the new JVM setting in the puppet logging.
The new value will not be active. As shown in the screenshot, it is still the old value.
![grabberraster 0168](https://cloud.githubusercontent.com/assets/7237078/16559253/01139176-41ec-11e6-8107-ebaed4f75b8f.jpg)

**Comment by biemond** [comment]
Hi,

if you set it on the domain creation, it will add those to the nodemanager startup property
https://github.com/biemond/biemond-orawls/blob/master/templates/domains/domain.py.erb#L122 plus set it on the adminserver.

you say you changed ADM, do you mean on the domain because that is 1time only ( it is not type and wlst is not so flexible), or did you recreate the VM.

after the domain creation you should do this
```
server_instances:
  'AdminServer':
    ensure:                                'present'
    arguments:
           - *server_vm_args_permsize
           - *server_vm_args_max_permsize
           - *server_vm_args_memory
           - *server_vm_args_max_memory
           - '-Dweblogic.Stdout=/var/log/weblogic/AdminServer.out'
           - '-Dweblogic.Stderr=/var/log/weblogic/AdminServer_err.out'
```

And then subscribe on this change and do a restart
