### ISSUE TITLE
Duplicate declaration of installation source file

### ISSUE THREAD

**Issue by rssh22** [biemond/biemond-orawls#411]
Hello!

I'm trying to create several installations of the same WebLogic Middleware in different middleware homes:
My hiera file looks like:
```yaml

middleware_homes:
 'wld-pro-03_1036':
   version: 1036
   filename: wls1036_generic.jar
   jdk_home_dir: /var/tmp/java-1.6.0_131
   oracle_base_home_dir: /puppet/oracle
   middleware_home_dir: /puppet/oracle/wld-pro-03_1036
   weblogic_home_dir: /puppet/oracle/wld-pro-03_1036/wlserver
   os_user: root
   os_group: root
   download_dir: /puppet/download
   source: /puppet
   
 'wld-pro-04_1036':
   version: 1036
   filename: wls1036_generic.jar
   jdk_home_dir: /var/tmp/java-1.6.0_131
   oracle_base_home_dir: /puppet/oracle
   middleware_home_dir: /puppet/oracle/wld-pro-04_1036
   weblogic_home_dir: /puppet/oracle/wld-pro-04_1036/wlserver
   os_user: root
   os_group: root
   download_dir: /puppet/download
   source: /puppet
   
 'wld-pro-05_1036':
   version: 1036
   filename: wls1036_generic.jar
   jdk_home_dir: /var/tmp/java-1.6.0_131
   oracle_base_home_dir: /puppet/oracle
   middleware_home_dir: /puppet/oracle/wld-pro-05_1036
   weblogic_home_dir: /puppet/oracle/wld-pro-05_1036/wlserver
   os_user: root
   os_group: root
   download_dir: /puppet/download
   source: /puppet   
```
But I'm getting this error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/puppet/download/wls1036_generic.jar] is already declared in file /etc/puppetlabs/code/environments/production/modules/orawls/manifests/weblogic_type.pp:162; cannot redeclare at /etc/puppetlabs/code/environments/production/modules/orawls/manifests/weblogic_type.pp:162 at /etc/puppetlabs/code/environments/production/modules/orawls/manifests/weblogic_type.pp:162:5 at /etc/puppetlabs/code/environments/production/modules/fussion/manifests/home.pp:3 on node puppet-pil00.msc.es
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

It is the expected behaviour or it is a bug? 

Regards,

Raúl
