### ISSUE TITLE
Issue wile creating work manager 

### ISSUE THREAD

**Issue by piusranjan** [biemond/biemond-orawls#420]
I wanted to create a workmanager  "wm/demoThreadpool" . I am using below puppet resource . But instead of  "wm/demoThreadpool" , it is creating workmanager as demoThreadpool. It seems it is taking the string value after  last slash (/) as work manager name . We have a requirement to keep (/) in work manager.

````
wls_work_managers:
 MyDemoDomain/wm/demoThreadPool:
    ensure: present
    capacity: CapacityConstraint
    maxthreadsconstraint: MaxThreadsConstraint
    minthreadsconstraint: MinThreadsConstraint
    fairsharerequestclass: FairShareReqClass
    stuckthreads: '1'
    target: '%{hiera(''targets'')}'
    targettype: '%{hiera(''targettypes'')}'
````
Your help is highly appreciated.
