### ISSUE TITLE
stuck in dependency cycle on clusters/datasource

### ISSUE THREAD

**Issue by mdplatts** [biemond/biemond-orawls#425]
Probably me doing it wrong and I apologise if this is the wrong place, but I'm getting the following error -

Error: Failed to apply catalog: Found 1 dependency cycle:
(Class[Datasources] => Wls_datasource[xxx/ClusterLeasingDataSource] => Wls_cluster[xxx/NameServerCluster] => Class[Cluster] => Class[Datasources])

I have this data source - 

```
datasource_instances:
  xxx/ClusterLeasingDataSource:
    ensure: present
    jndinames: ClusterLeasingDataSource
    drivername: oracle.jdbc.driver.OracleDriver
    globaltransactionsprotocol: None
    usexa: '0'
    initialcapacity: '2'
    maxcapacity: 50
    testtablename: 'SQL SELECT 1 FROM DUAL'
    target:
      - NameServerCluster
    targettype:
      - Cluster
```

And this cluster definition -

```
cluster_instances:
  xxx/NameServerCluster:
    ensure: present
    messagingmode:              'unicast'
    #migrationbasis:             'database'
    migrationbasis:             'consensus'
    #migration_datasource:       'ClusterLeasingDataSource'
    servers:
      - 'ns_1'
      - 'ns_2'
      - 'ns_3'
```

If I leave it as 'consensus' then puppet runs but if I change it to "database" and "ClusterLeasingSource" then I get the dependency error. I'm trying to do that to see if I can get a 3-node cluster to run as a one node cluster (e.g. in the event of the failure of two of the three AZ's in our AWS account).  I can reduce 3 to 2 nodes but not 2 to 1 (or even reboot the one) and someone suggested I try switching to database. 

I'd also want to use the data source for mutliple different clusters - which given the "migration_table_name" value I'm presuming it should be possible to share a schema and just have several tables in the one place.

**Comment by biemond** [comment]
Hi 

you got the chicken and egg situations
but you can always assign the datasource to the cluster nodes (servers) instead of cluster. That also works.

thanks

**Comment by mdplatts** [comment]
Thanks - I tried that and it still reports the same as if its ignored the changes (unless I misunderstood which is always an option) - 
```
datasource_instances:
  xxx/ClusterLeasingDataSource:
    ensure: present
    jndinames: ClusterPool
    drivername: oracle.jdbc.driver.OracleDriver
    globaltransactionsprotocol: None
    usexa: '0'
    initialcapacity: '2'
    maxcapacity: '50'
    testtablename: 'SQL SELECT 1 FROM DUAL'
    target:
      - ns_1
      - ns_2
      - ns_3
    targettype:
      - Server
      - Server
      - Server
```
The graph remains the same as if its ignored the changes - 
```
digraph Resource_Cycles {
  label = "Resource Cycles"
"Class[Datasources]" -> "Wls_datasource[strata/ClusterLeasingDataSource]" -> "Wls_cluster[xxx/EchCluster]" -> "Class[Cluster]" -> "Class[Datasources]"
"Class[Datasources]" -> "Wls_datasource[strata/ClusterLeasingDataSource]" -> "Wls_cluster[xxx/NameServerCluster]" -> "Class[Cluster]" -> "Class[Datasources]"
"Class[Datasources]" -> "Wls_datasource[strata/ClusterLeasingDataSource]" -> "Wls_cluster[xxx/SICluster]" -> "Class[Cluster]" -> "Class[Datasources]"
"Class[Datasources]" -> "Wls_datasource[strata/ClusterLeasingDataSource]" -> "Wls_cluster[xxx/XxxCluster]" -> "Class[Cluster]" -> "Class[Datasources]"
"Class[Datasources]" -> "Wls_datasource[strata/ClusterLeasingDataSource]" -> "Wls_cluster[xxx/SupCluster]" -> "Class[Cluster]" -> "Class[Datasources]"
}
```
